# Hibernate development configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing_api
spring.datasource.username=compose-postgres
spring.datasource.password=compose-postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always

cors.allowed-origins=http://localhost:5173,http://localhost:8080