spring.application.name=ticketing-api

# *** Logs ***
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.github.loickcherimont.ticketing_api=DEBUG

# Load environment variables to use them
spring.config.import=optional:file:.env.properties

# Hibernate configurations
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# *** Swagger and API docs ***

# Custom configs for API docs and Swagger UI 
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# To sort the routes in Swagger using alphabetical order
springdoc.swagger-ui.tagsSorter=alpha

# Spring Boot follow Railway's X-Forwarded-Proto headers
# If Railway sends HTTPS, Spring Boot sends HTTPS to
server.forward-headers-strategy=framework

# Spring Security custom properties
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time=3600000