spring.application.name=ticketing-api

# *** Logs ***
logging.level.root=ERROR
logging.level.com.github.loickcherimont.ticketing_api=DEBUG
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# Hibernate configurations
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# *** Swagger and API docs ***

# Custom configs for API docs and Swagger UI 
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-custom.html

# To sort the routes in Swagger using alphabetical order
springdoc.swagger-ui.tagsSorter=alpha